### ISSUE TITLE
ENOENT

### ISSUE THREAD

**Issue by KaKi87** [Emano-Waldeck/download-by#3] opened 2018-09-06 11:01 UTC
Hi,

The following path is set in the plugin : `%ProgramFiles(x86)%\Internet Download Manager\IDMan.exe`
And it's the good one, if I execute that directly on Windows, it works.

But the plugin is returning a ENOENT error :
![2018-09-06 12_58_31-download by internet download manager - chrome web store](https://user-images.githubusercontent.com/21284089/45153630-f9fb9e00-b1d4-11e8-8a9b-ceb9869c7dff.png)

Thanks !

**Comment by Emano-Waldeck** [comment] 2018-09-06 14:49
how about `%ProgramFiles(x86)%\\Internet Download Manager\\IDMan.exe`

**Comment by Emano-Waldeck** [comment] 2018-09-06 14:49
also try `"%ProgramFiles(x86)%\Internet Download Manager\IDMan.exe"`

**Comment by KaKi87** [comment] 2018-09-07 07:16
![2018-09-07 09_13_58-](https://user-images.githubusercontent.com/21284089/45204114-8f06a180-b27e-11e8-986c-b7428471b071.png)

I don't know why this happens so many times but it's not acceaptable... Please fix it :)

**Comment by claudiopq23** [comment] 2018-11-01 17:41
![img-20160705-wa0001](https://user-images.githubusercontent.com/30656428/47868853-1b979100-dde4-11e8-8560-acf3830887ed.jpg)
Duplicate of #

**Closed** 2020-01-21 09:17 UTC
